### ISSUE TITLE
transferFromMultisigToHtlc fails if balance of eth sender is lower than the value to transfer

### ISSUE THREAD

**Issue by jsappme** [Trinkler/agora-swap#22]
Please provide the following information:

### Expected behaviour

transferFromMultisigToHtlc should succeed no matter the balance of the sender is. it should check the balance of the multisig instead.

{"sender":"0x63aD4a1437070a7ED0FE4785E7778cdFa3e4CF37","msigId":"0x5033eba5c075f402da4f47e31c3d3cc6a452ca09e858de894fdc629ab181bd4c","recipient":"0x83E4aBB4B9EDE83dEf966b234a3BD19B00cccEC4","value":"0.0001","hash":{"type":"Buffer","data":[19,25,144,173,242,57,2,18,244,61,185,197,59,147,108,233,4,96,232,39,116,15,59,157,58,160,177,249,228,225,106,130]},"timeout":1800}

### Actual behaviour

it checks of the balance of the eth wallet address instead of checking the balance of the eth multisig.

### Reproduction steps

Try to buy NIM with almost no eth in the wallet address.

### Information about our environment

* OS & Verison
* Browser & Version
* Parity version
* ... other helpful information

**Comment by retotrinkler** [comment]
@jsappme this should be as intended. can this issue be closed?
